Merge latest win32-pr changes from main to live (#2933)
* Update common-control-versions.md

Adds table formatting for "Common Control DLL Versions Numbers". The content hasn't otherwise been changed.

* Update resource-file-formats.md

Mention *RT_ANICURSOR* and *RT_ANIICON*

* Update resource-file-formats.md

* Update resource-file-formats.md

* Update using-cursors.md

* Update using-cursors.md

* Update using-cursors.md

* Fixed bug in example in 3d-perspective-transform.md

Changes in the example to use Vector2F instead of Vector3F.

* Update cng-mlkem-examples.md (#2910)

The description in the first two paragraphs was incorrect, referring to signing and verifying digital signatures. This is what ML-DSA is used for but not ML-KEM. Corrected the first intro paragraph and combined the second two.

* Fix broken link in VBS Enclaves dev guide (#2914)

Fixing broken link to EnclaveCopyOutOfEnclave fn in API ref docs.

* Update kernel-checks-for-non-whql-signed-drivers.md (#2616)

updating Sysdev to Hardware Developer Program (HDC)

* Update publishing-your-event-schema-for-a-manifest-base-provider.md

Attempting to compile the manifest with `mc.exe manifest.man` leads to the following error:
`For <data> element 'Image', the prefix of 'win:Pointer' is not in the winmeta namespace.`

Changing the https://manifests.microsoft.com/win/2004/08/windows/events URL to http://manifests.microsoft.com/win/2004/08/windows/events (https to http) seem to fix this problem.

* Update writing-manifest-based-events.md to fix const cast errors

Change string type from LPWSTR to LPCWSTR to fix compiler errors like this:
```
error C2440: 'initializing': cannot convert from 'const wchar_t []' to 'LPWSTR' errors
```

* Update publishing-your-event-schema-for-a-manifest-base-provider.md to make events appear in Event Viewer

The sample provider is currently hard to test, since events doesn't show up in Event Viewer. Therefore, proposing to map the events to the in-built "Application" channel, so that it shows up in the Event Viewer "Application" folder.

* Update writing-manifest-based-events.md to fix pointer truncation warning

* Update resource-file-formats.md

* Update writing-manifest-based-events.md with int wmain return-type

Fixes the following warning when building with the Visual Studio 2022 C++ compiler:
>Main.cpp(28,6): warning C4326: return type of 'wmain' should be 'int' instead of 'void'

* Update symstore-command-line-options.md

* Update symstore-command-line-options.md

* Update about-keyboard-input.md

Update HID Usage Names according to current HID Usage Tables 1.6 json (attached to spec PDF file)

* Add ABGR32 to input formats of MFVP (#2056)

* Update symstore-command-line-options.md

* Correct quotes in pre-formatted examples

Signed-off-by: ss <kotbegemoth@gmail.com>

* more fixes

* Fix a few typos (#2059)

* Fix a few typos

* Fix quote

* Fix "&quot;" inside of code blocks

* Some terminology updates, and a tweak to a topic (#2930)

* Fix quotes in pre-formatted examples

Wrote a script to find `&quot;` inside preformatted markdown blocks - this should correct all of them.

`&quot;` usage in WMDM\compiling-the-sample-service-provider-using-visual-studio.md is intentional and needs no correction.

Signed-off-by: ss <kotbegemoth@gmail.com>

* Add links to FIPS 203 source on nist.gov

* Update desktop path to win32 to avoid redirect

* Initialize Docs repository: https://github.com/MicrosoftDocs/win32-pr of branch main

* Add ABGR32 to input formats of MFVP (#2056) (#2923)

Co-authored-by: Chunbo <chunbo.hua@intel.com>
Co-authored-by: Learn Build Service GitHub App <Learn Build Service LearnBuild@microsoft.com>

* Updates to PQC BCrypt / NCrypt documentation (#2926)

* Initial updates to PQC BCrypt / NCrypt documentation

* Address some PR comments and further tidying

+ Still need to do more in-depth tidying of the code samples

* Address some more comments

* Add requirements section to ncrypt/bcrypt APIs

* Link to FIPS 203 on nist.gov

---------

Co-authored-by: Alvin Ashcraft <aashcraft@microsoft.com>

---------

Signed-off-by: ss <kotbegemoth@gmail.com>
Co-authored-by: Tim Weis <tim-weis@users.noreply.github.com>
Co-authored-by: Dimitriy Ryazantcev <dimitriy.ryazantcev@gmail.com>
Co-authored-by: learn-build-service-prod[bot] <113403604+learn-build-service-prod[bot]@users.noreply.github.com>
Co-authored-by: nikolaycode <46713216+nikolaycode@users.noreply.github.com>
Co-authored-by: Jess Krynitsky <jekrynit@microsoft.com>
Co-authored-by: Learn Build Service GitHub App <Learn Build Service LearnBuild@microsoft.com>
Co-authored-by: Steven White <31261191+stevewhims@users.noreply.github.com>
Co-authored-by: Cymoki <Cymoki@Microsoft.com>
Co-authored-by: Fredrik Orderud <forderud@users.noreply.github.com>
Co-authored-by: Jim Walker <jimwalk@microsoft.com>
Co-authored-by: KB <12849639+Karl-Bridge-Microsoft@users.noreply.github.com>
Co-authored-by: Fredrik Orderud <fredrik.orderud@gehealthcare.com>
Co-authored-by: Jonathan David Moore <jdm7dv@virginia.edu>
Co-authored-by: Chunbo <chunbo.hua@intel.com>
Co-authored-by: ss <kotbegemoth@gmail.com>
Co-authored-by: Blake-Madden <66873089+Blake-Madden@users.noreply.github.com>
Co-authored-by: huypub <38988242+huypub@users.noreply.github.com>
Co-authored-by: Samuel Lee <56448320+samuel-lee-msft@users.noreply.github.com>