Prevent compilation failure with error C2664
Using the provided code sample leads compilation to fail with
`error C2664: 'void printError(TCHAR *)': cannot convert argument 1 from 'const wchar_t [...]' to 'TCHAR *'`
messages in a C++ console application project created under Visual Studio Community 17.2.5, where the `permissive-` flag is used by default.