Minor change to fix compile time error
To Reproduce: Compile as a C++ project with Visual Studio 2019 (v142) 
Result: error C2440: 'initializing': cannot convert from 'const char [15]' to 'char *'
Expected: No error when compiling
Fix: Change char* to const char*