RPC tutorial: Fix const errors
Fixes errors like this when building with VS2022:
error C2440: 'initializing': cannot convert from 'const char [9]' to 'unsigned char *'