Update writing-manifest-based-events.md to fix const cast errors
Change string type from LPWSTR to LPCWSTR to fix compiler errors like this:
```
error C2440: 'initializing': cannot convert from 'const wchar_t []' to 'LPWSTR' errors
```